# Generated by Django 6.0 on 2025-12-09 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_registration_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='student',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sms_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_sent_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_st_status_5e2210_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['education_level'], name='students_st_educati_0d2ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['ward'], name='students_st_ward_b78799_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['sms_status'], name='students_st_sms_sta_2406ab_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['date_applied'], name='students_st_date_ap_c785ab_idx'),
        ),
    ]
