# Generated by Django 6.0 on 2025-12-09 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_options_student_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_no',
            field=models.CharField(help_text="Student's school registration/admission number", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sms_status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('sent', 'Sent'), ('failed', 'Failed'), ('partial', 'Partial')], default='not_sent', max_length=20),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['registration_no'], name='students_st_registr_5bb7fe_idx'),
        ),
    ]
